<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\NewFolder\**" />
    <Content Remove="Controllers\NewFolder\**" />
    <EmbeddedResource Remove="Controllers\NewFolder\**" />
    <None Remove="Controllers\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2025.7.1" />
    <PackageReference Include="Stripe.net" Version="48.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\profiles\" />
    <Folder Include="wwwroot\images\products\" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="Path\To\ConflictingFile.cs" />
	</ItemGroup>

</Project>
